config/routes.rb
 Rails.application.routes.draw do
  	get 'news/index',as:'news'
	require 'sidekiq/web'
	authenticate :user, lambda { |u| u.roles.include? :admin } do
		mount Sidekiq::Web => '/sidekiq'
	end
	mount Ckeditor::Engine => '/ckeditor'
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :notifications,except: [:new, :create, :edit, :update, :destroy, :show] do 
		collection do
			post 'seen',to:'notifications#seen'
		end
	end

	resources :friendship do
		collection do
			get 'allUsers'
			get 'blockedUsers'
			get 'pendingUsers'
		end
		member do 
			get 'showUser'
			get 'addFriend'
			post 'decision/:status/:received_from',to:'friendship#decision',as:"decision"
			post 'block'
			post 'unblock'
			post 'unfriend'
		end
	end

	resources :comments,except: [:index,:new, :create, :edit, :update, :destroy, :show]do
		collection do
			get 'index/:id',to:'comments#index',as: :all
		end
		member do
			get 'new',to:'comments#new', as: :new
			post 'create',to:'comments#create', as: :create
		end
	end
	resources :communities do
		collection do
			get 'public',to:'communities#public'
			get 'private',to:'communities#private_club'
			get 'owned',to:'communities#owned_club'
			post 'toggle_club_admin'
		end
		member do 
			post 'join',to:'communities#join_public'
			post 'requested',to:'communities#ask_private'
			post 'approve_invite/:invitee_id/:status/:invitation',to:'communities#approve_invite',as:"accept_member_into"
			get 'posts'
			get 'members'
			get 'boss'
			get 'invitations'
		end
	end
	 
	resources :profile, except: [:new, :create, :edit, :update, :destroy, :index] do
		collection do
		  patch 'update'
		  get 'edit'
		  post 'update_bio'
		  get "profile_image_carousel",as:"profile_carousel"
		  post "image",as:'image_upload'
		  get 'close_carousel',as:"close_carousel"
		  post 'dp/:id',to:'profile#make_dp',as:"make_profile_image"
		  get "cover_image_carousel",as:"cover_carousel"
		  post "cover_image",as:'cover_image_upload'
		  get 'close_carousel_cover',as:"close_carousel_cover"
		  post 'cover/:id',to:'profile#make_cover',as:"make_cover_image"
		end
	end

	resources :preferences do
		collection do
		  get 'change_panel_color'
		  get 'toggle_background_image'
		  get 'toggle_right_panel'
		  get 'set_background_image'
		end
	end

	resources :blogs do
	end
	
	resources :chatrooms do
		resource :chatroom_users
		resources :messages
		collection do
			get 'all_users'
			post 'get_users_chatroom'
		end
	end

	devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
	root "communities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/lbd4/_footer.html.erb
<footer class="footer">
    <p class="copyright text-center">
       <%=Platipus::Renderer.copyright 'Faraz Noor & Dhruv Raj', 'All rights reserved'%>
    </p>    
</footer>

app/views/lbd4/_kachra.html.erb
<form>
                                        <div class="row">
                                            <div class="col-md-5 pr-1">
                                                <div class="form-group">
                                                    <label>Company (disabled)</label>
                                                    <input type="text" class="form-control" disabled="" placeholder="Company" value="Creative Code Inc.">
                                                </div>
                                            </div>
                                            <div class="col-md-3 px-1">
                                                <div class="form-group">
                                                    <label>Username</label>
                                                    <input type="text" class="form-control" placeholder="Username" value="michael23">
                                                </div>
                                            </div>
                                            <div class="col-md-4 pl-1">
                                                <div class="form-group">
                                                    <label for="exampleInputEmail1">Email address</label>
                                                    <input type="email" class="form-control" placeholder="Email">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6 pr-1">
                                                <div class="form-group">
                                                    <label>First Name</label>
                                                    <input type="text" class="form-control" placeholder="Company" value="Mike">
                                                </div>
                                            </div>
                                            <div class="col-md-6 pl-1">
                                                <div class="form-group">
                                                    <label>Last Name</label>
                                                    <input type="text" class="form-control" placeholder="Last Name" value="Andrew">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Address</label>
                                                    <input type="text" class="form-control" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4 pr-1">
                                                <div class="form-group">
                                                    <label>City</label>
                                                    <input type="text" class="form-control" placeholder="City" value="Mike">
                                                </div>
                                            </div>
                                            <div class="col-md-4 px-1">
                                                <div class="form-group">
                                                    <label>Country</label>
                                                    <input type="text" class="form-control" placeholder="Country" value="Andrew">
                                                </div>
                                            </div>
                                            <div class="col-md-4 pl-1">
                                                <div class="form-group">
                                                    <label>Postal Code</label>
                                                    <input type="number" class="form-control" placeholder="ZIP Code">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>About Me</label>
                                                    <textarea rows="4" cols="80" class="form-control" placeholder="Here can be your description" value="Mike">Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-info btn-fill pull-right">Update Profile</button>
                                        <div class="clearfix"></div>
                                    </form>

app/views/lbd4/_nav.html.erb
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
    <div class=" container-fluid  ">
        <%unless current_user%>
        <a class="navbar-brand" href=""> User </a>
        <%else%>
        <%=link_to current_user.display_name , profile_path(current_user),class:"navbar-brand",remote:true%>
        <%end%>
        <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
            <span class="navbar-toggler-bar burger-lines"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <ul class="nav navbar-nav mr-auto">
                <li class="dropdown nav-item">
                    <a id="notification_button" class="dropdown-toggle nav-link" data-toggle="dropdown" onclick="read_notification();">
                        <i class="nc-icon nc-planet"></i>
                    <%if current_user%>
                        <%notify=current_user.notifications.unread%>

                        <span class="notification" id="notification_count"><%=notify.length%></span>
                        <span class="d-lg-none" id="notification_count_2">Notification</span>
                        
                    </a>
                    <ul class="dropdown-menu" id="notification_area">
                        <%=render 'shared/notifications',notifications:notify%>
                    </ul>
                    <%end%>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nc-icon nc-zoom-split"></i>
                        <span class="d-lg-block">&nbsp;Search</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" onclick="get_users_account_edit();" style="cursor: pointer;">
                        <span class="no-icon">Account</span>
                    </a>
                </li>
                <%if logged_in?(:admin)%>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="https://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="no-icon">Admin</span>
                    </a>
                    
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        
                        <%=link_to "Admin", rails_admin_path,class:"dropdown-item",target:"_blank"%>
                        <div class="divider"></div>
                        <%=link_to "Sidekiq", sidekiq_web_path,class:"dropdown-item",target:"_blank"%>
                    </div>
                    
                </li>
                <%end%>
                <li class="nav-item">
                    <%=link_to "Logout",destroy_user_session_path,method: :delete,class:"nav-link" if current_user%>
                </li>
            </ul>
        </div>
    </div>
</nav>
<script type="text/javascript">
function read_notification(){
    $.ajax({
      type:"post",
      url:'<%=seen_notifications_path%>',
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    })
}
</script>

app/views/lbd4/_preferences.html.erb
<script type="text/javascript">
    function change_panel_color(color)
    {
        domain_name=window.location.origin;
        $.ajax({
            type:"get",
            url: domain_name+"/preferences/change_panel_color?color="+color
        })
    }
    function toggle_background_image()
    {
        domain_name=window.location.origin;
        $.ajax({
            type:"get",
            url: domain_name+"/preferences/toggle_background_image"
        })
    }
    function toggle_right_panel()
    {
        domain_name=window.location.origin;
        $.ajax({
            type:"get",
            url: domain_name+"/preferences/toggle_right_panel"
        })
    }
    function set_background_image(asset_name)
    {
        domain_name=window.location.origin;
        $.ajax({
            type:"get",
            url: domain_name+"/preferences/set_background_image?asset_name="+asset_name
        })
    }
</script>
<%user_prefs=current_user.preference%>
<div class="fixed-plugin">
    <div class="dropdown show-dropdown">
        <a href="#" data-toggle="dropdown">
            <i class="fa fa-cog fa-2x"> </i>
        </a>
        <ul class="dropdown-menu">
            <li class="header-title"> Sidebar Style</li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger">
                    <p>Background Image</p>
                    
                    <label class="switch" style="float: right;">
                      <input type="checkbox" <%="checked" if !user_prefs.display_panel_image.nil? and user_prefs.display_panel_image%> onclick="toggle_background_image();">
                      <span class="slider round"></span>
                    </label>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger">
                    <p>Right Panel Show</p>
                    
                    <label class="switch" style="float: right;">
                      <input type="checkbox" <%="checked" if !user_prefs.display_right_panel.nil? and user_prefs.display_right_panel%> onclick="toggle_right_panel();">
                      <span class="slider round"></span>
                    </label>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <p>Filters</p>
                    <div class="pull-right">
                        <span class="badge filter badge-black" data-color="black" onclick="change_panel_color($(this).attr('data-color'));">&nbsp;</span>
                        <span class="badge filter badge-azure" data-color="azure" onclick="change_panel_color($(this).attr('data-color'));">&nbsp;</span>
                        <span class="badge filter badge-green" data-color="green" onclick="change_panel_color($(this).attr('data-color'));">&nbsp;</span>
                        <span class="badge filter badge-orange" data-color="orange" onclick="change_panel_color($(this).attr('data-color'));">&nbsp;</span>
                        <span class="badge filter badge-red" data-color="red" onclick="change_panel_color($(this).attr('data-color'));">&nbsp;</span>
                        <span class="badge filter badge-purple" data-color="purple" onclick="change_panel_color($(this).attr('data-color'));">&nbsp;</span>
                    </div>
                    <script type="text/javascript">
                        $('.badge-<%=user_prefs.panel_color%>').addClass("active");
                    </script>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="header-title">Sidebar Images</li>
            <!-- here we will show them the list of images as cover pics uploaded by the user -->
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="<%=image_url('sidebars/sidebar-1.jpg')%>" id="sidebar-1" alt="" onclick="set_background_image('sidebar-1.jpg');" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="<%=image_url('sidebars/sidebar-2.jpg')%>" id="sidebar-2" alt="" onclick="set_background_image('sidebar-2.jpg');" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="<%=image_url('sidebars/sidebar-3.jpg')%>" id="sidebar-3" alt="" onclick="set_background_image('sidebar-3.jpg');" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="<%=image_url('sidebars/sidebar-4.jpg')%>" id="sidebar-4" alt="" onclick="set_background_image('sidebar-4.jpg');" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="<%=image_url('sidebars/sidebar-5.jpg')%>" id="sidebar-5" alt="" onclick="set_background_image('sidebar-5.jpg');" />
                </a>
            </li>
            <%unless user_prefs.image_selected.nil?%>
            <script type="text/javascript">
                $("#<%=user_prefs.image_selected.split('.').first%>").parent().parent().addClass('active');
            </script>
            <%end%>
        </ul>
    </div>
</div>

app/views/lbd4/_sidebar.html.erb
<%user_prefs=current_user.preference
image_name=user_prefs.image_selected
image_name||=""%>
<div class="sidebar" data-image="<%=(!user_prefs.display_panel_image.nil? and user_prefs.display_panel_image and !image_name.empty?) ? image_url("sidebars/#{image_name}") : ''%>" data-color="<%=user_prefs.panel_color%>">
    
    <div class="sidebar-wrapper">
        <div class="logo">
            <%=link_to "BootUp",root_path,class:"simple-text",remote:true%>
        </div>
        <ul class="nav master_navs">
            <li>
                <%=link_to '<i class="nc-icon nc-album-2"></i><p>Timeline</p>'.html_safe,profile_path(current_user),class:"nav-link",id:"timeline_nav",remote: true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Loading Timeline',text_color: 'gold').html_safe%>
            </li>
            <li class="nav-item">
                <%=link_to '<i class="nc-icon nc-paper-2"></i><p>News Feed</p>'.html_safe,news_path,class:"nav-link",id:"timeline_nav",remote: true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Loading News',text_color: 'gold').html_safe%>
            </li>
            <li class="nav-item">
            <%=link_to '<i class="nc-icon nc-vector"></i><p>Clubs</p>'.html_safe,communities_path,class:"nav-link",id:"communities_nav",remote: true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Loading Clubs',text_color: 'gold').html_safe%>


            </li>
            <li class="nav-item">
                <%=link_to '<i class="nc-icon nc-grid-45"></i><p>Friends</p>'.html_safe,friendship_index_path,class:"nav-link",id:"friendship_nav",remote: true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Loading Friends',text_color: 'gold').html_safe%>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="./icons.html">
                    <i class="nc-icon nc-vector"></i>
                    <p>Icons</p>
                </a>
            </li> -->
            <li class="nav-item">
                <a class="nav-link" href="chatrooms" target="_blank">
                    <i class="nc-icon nc-chat-round"></i>
                    <p>ChatBox</p>
                </a>
            </li>
            <li class="nav-item">
                <%=link_to '<i class="nc-icon nc-bell-55"></i><p>Notifications</p>'.html_safe,notifications_path,class:'dropdown-item nav-link',remote: true%>
            </li>
        </ul>
    </div>
</div>

app/views/lbd4/_user_details.html.erb
<div class="card-image">
    <img id="cover_picture" src="<%=cover_display_image(current_user)%>" alt="..." style="background-image:url('https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400');background-repeat: no-repeat;" alt="...">
</div>
<div class="card-body">
    <div class="author">
        <a href="#">
            <div class= "profile_pic_bg">
                <img id="profile_picture" class="avatar border-gray" src="<%=profile_display_image(current_user)%>" alt="..." style="background-image:url('<%=asset_path('default_logos/default_profile.png')%>');background-repeat: no-repeat;"/>
                    <div class="profile_edit_overlay">
                        <%=link_to ("<h5><strong><i class='nc-icon nc-ruler-pencil'></i></strong></h5>").html_safe,edit_profile_index_path,remote: :true if current_user%>
                    </div>
            </div>
            <div class="profile_edit_overlay">
                <%=link_to ("<h5>"+current_user.display_name+"</h5>").html_safe,edit_profile_index_path,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Edit Profile',text_color: 'green').html_safe,remote: :true if current_user%>
            </div>
        </a>
        <p class="description">
            <%=current_user.email%>
        </p>
    </div>
    <p class="description text-center">
        <%bio_display=(current_user.profile.bio.nil?) ? "My Bio" : current_user.profile.bio%>
        <center>
        <span class="description text-center" id="user_bio" style="width:100%;"><i><b>"</b><span onclick="edit_bio()" style="cursor: pointer"><%=bio_display%></span><b>"</b></i></span>
        </center>
    </p>
</div>
<hr>
<div class="button-container mr-auto ml-auto">
    <button href="#" class="btn btn-simple btn-link btn-icon">
        <i class="fa fa-facebook-square"></i>
    </button>
    <button href="#" class="btn btn-simple btn-link btn-icon">
        <i class="fa fa-twitter"></i>
    </button>
    <button href="#" class="btn btn-simple btn-link btn-icon">
        <i class="fa fa-google-plus-square"></i>
    </button>
</div>
<%=render 'shared/user_details_js'%>