config/routes.rb
 Rails.application.routes.draw do
  	get 'news/index',as:'news'
	require 'sidekiq/web'
	authenticate :user, lambda { |u| u.roles.include? :admin } do
		mount Sidekiq::Web => '/sidekiq'
	end
	mount Ckeditor::Engine => '/ckeditor'
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :notifications,except: [:new, :create, :edit, :update, :destroy, :show] do 
		collection do
			post 'seen',to:'notifications#seen'
		end
	end

	resources :friendship do
		collection do
			get 'allUsers'
			get 'blockedUsers'
			get 'pendingUsers'
		end
		member do 
			get 'showUser'
			get 'addFriend'
			post 'decision/:status/:received_from',to:'friendship#decision',as:"decision"
			post 'block'
			post 'unblock'
			post 'unfriend'
		end
	end

	resources :comments,except: [:index,:new, :create, :edit, :update, :destroy, :show]do
		collection do
			get 'index/:id',to:'comments#index',as: :all
		end
		member do
			get 'new',to:'comments#new', as: :new
			post 'create',to:'comments#create', as: :create
		end
	end
	resources :communities do
		collection do
			get 'public',to:'communities#public'
			get 'private',to:'communities#private_club'
			get 'owned',to:'communities#owned_club'
			post 'toggle_club_admin'
		end
		member do 
			post 'join',to:'communities#join_public'
			post 'requested',to:'communities#ask_private'
			post 'approve_invite/:invitee_id/:status/:invitation',to:'communities#approve_invite',as:"accept_member_into"
			get 'posts'
			get 'members'
			get 'boss'
			get 'invitations'
		end
	end
	 
	resources :profile, except: [:new, :create, :edit, :update, :destroy, :index] do
		collection do
		  patch 'update'
		  get 'edit'
		  post 'update_bio'
		  get "profile_image_carousel",as:"profile_carousel"
		  post "image",as:'image_upload'
		  get 'close_carousel',as:"close_carousel"
		  post 'dp/:id',to:'profile#make_dp',as:"make_profile_image"
		  get "cover_image_carousel",as:"cover_carousel"
		  post "cover_image",as:'cover_image_upload'
		  get 'close_carousel_cover',as:"close_carousel_cover"
		  post 'cover/:id',to:'profile#make_cover',as:"make_cover_image"
		end
	end

	resources :preferences do
		collection do
		  get 'change_panel_color'
		  get 'toggle_background_image'
		  get 'toggle_right_panel'
		  get 'set_background_image'
		end
	end

	resources :blogs do
	end
	
	resources :chatrooms do
		resource :chatroom_users
		resources :messages
		collection do
			get 'all_users'
			post 'get_users_chatroom'
		end
	end

	devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
	root "communities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_dropzone.html.erb
<script type="text/javascript">
$("#mydropzone_<%=type%>").dropzone({
    url: "<%=url%>",
    addRemoveLinks : false,
    maxFilesize: 5,
    maxFiles:1,
    dictResponseError: 'Error uploading file!',
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    },
      success: function(file, response){
       $('#<%=type%>_picture').attr("src",file.dataURL);
       $.ajax({
       	type:"get",
       	url:"<%=close_corousel_url%>"
       })
    }
}).html("<div class='dz-default dz-message'><span><span class='deboss'>Drag and Drop File Here </span>/ <span class='dz-clickable' id='browsebtn'>Browse</span></span></div>");
$('#mydropzone_<%=type%>').addClass("dropzone");

</script>

<div class="logowrp clearfix" id="upload_area_<%=type%>">

	<div class="pull-left logowrpLeft">
	 <div class="pull-left" > 
	 <%latest_image_url=type=="profile" ? profile_display_image(current_user) : cover_display_image(current_user)%>
	 	<img src="<%=latest_image_url%>" height="59" width="59">
	 </div>
		<div class="logowrpLefttext">
			<%if image_count>1%>
				<%=link_to "+#{image_count-1}",profile_carousel_url,remote:true%>
			<%end%>		
		</div>
		<div class="Logodivider">OR</div>
		
	</div>
	<div class="pull-right logowrpRight">
	  	
		  	<div id="mydropzone_<%=type%>" style="width: 100%;height: 100%;padding: 15px 0 15px 0">	
			</div>
		
	</div>
</div>

app/views/shared/_enablers.html.erb
<%enablers.each do |enabler|%>
	<%enabler_obj=enabler.enable%>
	<div class="timeline_post_card <%=current_user.preference.display_right_panel ? 'col-md-12' : 'col-md-6' %>" id="<%=enabler_obj.class.name.downcase%>_<%=enabler_obj.id%>">
		<div class="card" style="padding: 30px;">
			<div class="card-body">
				<div style="padding: 0 0 15px 0px;">
				<img id="profile_picture" class="" src="<%=profile_display_image(enabler.author)%>" alt="..." height="44" width="44" style="background-image:url('<%=asset_path('default_logos/default_profile.png')%>');background-repeat: no-repeat;border-radius: 50%"/>
				<label style="vertical-align: text-bottom;padding-left: 10px;">
					
					<%= link_to enabler.author.name,profile_path(enabler.author),remote: true%>
					<%unless enabler.author.timeline == enabler.timeline%>
						
							<%if enabler.timeline.timeable.class.to_s == 'User'%>
								&nbsp;
								>
								&nbsp;
								<%= link_to enabler.timeline.timeable.name,profile_path(enabler.timeline.timeable),remote: true%>
											
							<% elsif enabler.timeline.timeable.class.to_s == 'Club'%>
								&nbsp;
								>
								&nbsp;
								<%= link_to "#{enabler.timeline.timeable.name}",community_path(enabler.timeline.timeable.id),remote: true%>
								
							<%end%>
					
					<%end%>

				</label>
				</div>
					<%case enabler_obj.class.to_s%>
					<%when 'Blog'%>
						<%=render partial:'blogs/blog_body',locals:{blog:enabler_obj}%>
					<%end%>
				<%if moderate_post_permission(enabler_obj,enabler.timeline) %>
					<%=link_to "Edit", edit_blog_path(enabler_obj),class:"card-link",remote: true%>
				<%end%>
				<%=link_to "Open", blog_path(enabler_obj),class:"card-link",remote: true%>
				<%=link_to "Comments", all_comments_path(enabler),class:"card-link",remote: true%>
			</div>
			<div class="card-footer">
				<div id="comment_form_title_<%=enabler.id%>"></div>
				<div id="comment_form_<%=enabler.id%>"></div>
				<div id="comments_<%=enabler.id%>"></div>
			</div>
		</div>
	</div>
	<hr>
<%end%>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 app-footer">
  	<%=Platipus::Renderer.copyright 'Faraz Noor & Dhruv Raj', 'All rights reserved'%>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    &nbsp;
    <%=link_to "Logout",destroy_user_session_path,method: :delete,class:"btn btn-outline-danger" if current_user%>
  </div>
</nav>

app/views/shared/_new_post.html.erb
<%=link_to "Blog", new_blog_path(timeline_id: @timeline.id), method: :get, remote: true,class:"dropdown-item" %>
<%=link_to "Media", media_new_path(timeline_id: @timeline.id), method: :get, remote: true,class:"dropdown-item" %>

app/views/shared/_notifications.html.erb
<%notifications.each do |notification|%>
		<%=render 'notifications/notification',notification:notification%>
<%end%>
<%=link_to 'Show All Notifications',notifications_path,class:'dropdown-item',remote: true%>

app/views/shared/_noty.html.erb
<%type||='success'%>
<script type="text/javascript">
	new Noty({
		timeout: 1000,
		type: '<%=type%>',
		layout: 'topCenter',
		text: '<%=message%>'
	}).show();
</script>

app/views/shared/_timeline.html.erb
<div id="form_title">
</div>
<div id="timeline_form">
</div>
<div class="row" id="post_viewport"></div>
<div class="row" id="timeline_viewport">
	<%unless @timeline_posts.nil?%>
		<%unless @timeline_posts.empty?%>
			<%=paginate @timeline_posts,remote:true%>
			<%=render 'shared/enablers',enablers:@timeline_posts%>
			<%=paginate @timeline_posts,remote:true%>
		<%else%>
			<center><%=image_tag asset_path('default_logos/nothing.png'),width:'100%',id:"empty_timeline_view" %></center>
		<%end%>
	<%else%>
		<center><%=image_tag asset_path('default_logos/nothing.png'),width:'100%',id:"empty_timeline_view" %></center>
	<%end%>
</div>

app/views/shared/_user.html.erb
<%owner_view||=false%>
<div class="d-flex flex-row border rounded">
    <div class="p-0 w-25">
        <%=image_tag user.profile_image.empty? ? asset_path('default_logos/default_profile.png') : user.profile_image ,class:"img-thumbnail border-0" rescue ""%>
    </div>
    <div class="pl-3 pt-2 pr-2 pb-2 w-75 border-left">
        <h4 class="text-primary"><%=user.display_name%></h4>
        <h5 class="text-info">
          
        <center>
        <span class="description text-center" style="width:100%;"><i><b>"</b><span style="cursor: pointer"><%=bio_display(user)%></span><b>"</b></i></span>
        </center>

        </h5>
        
      <%=link_to "View Profile" , profile_path(user.id),class:"btn btn-primary",remote:true%>
      <div style="padding: 20px 0px;">
          <%if owner_view%>
                <span style="padding: 0px 10px 0px 0px;">Club Admin</span>
                
                <label class="switch" style="">
                  <input type="checkbox" <%="checked" if @club.has_admin?(user)%> onclick="toggle_club_admin('<%=@club.id%>','<%=user.id%>');">
                  <span class="slider round"></span>
                </label>
          <%end%>
      </div>
  </div>
</div>

app/views/shared/_user_card.html.erb
<div class="card" id="user_card_<%=user.id%>" style="width: 100%;">
  <%=image_tag user.profile_image.empty? ? asset_path('default_logos/default_profile.png') : user.profile_image ,class:"card-img-top" rescue ""%>
  <div class="card-body">
    <h5 class="card-title"><%=link_to user.display_name , profile_path(user),remote:true%></h5>
    	<%unless current_user.blocked_friends.include?(user)|| current_user.friends_with?(user) %>
    		<span id="user_<%=user.id%>">
    			<%if current_user.pending_friends.include? user%>
    				<label style='color:orange;'>Request Sent</label>
    			<%elsif current_user.requested_friends.include? user%>
    				<%=link_to "Accept" , decision_friendship_path(id:user,status:1,received_from:'user_listing'),method: :post,remote:true%>
    				<%=link_to "Reject" , decision_friendship_path(id:user,status:0,received_from:'user_listing'),method: :post,remote:true%>
    			<%else%>	
    				<%=link_to "Add Friend" , addFriend_friendship_path(user),remote:true%>
    			<%end%>
    		</span>
    	<%end%>
  </div>
</div>

app/views/shared/_user_details.html.erb
<div class="card" style="width: 18rem;height:82vh;">
<div class="profile_pic_bg">
  <center>
    <img class="card-img-top" id="profile_picture" src="<%=profile_display_image(current_user)%>" alt="Card image cap" height="200" style="border-radius: 50%; width:65%;padding-top: 5%;">
    <div class="profile_edit_overlay">
    <%#edit_profile_image="<img src='#{asset_path('default_logos/edit_profile.png')}' alt='Edit Profile' height='30' width='30' title='Edit Profile'>"%>
    <%=link_to "<h5>Edit Profile</h5>".html_safe,edit_profile_index_path,remote: :true if current_user%>
  </div>
  </center>
</div>
  <div class="card-body">
    <h5 class="card-title"><%=current_user.display_name%></h5>
    <%bio_display=(current_user.profile.bio.nil?) ? "My Bio" : current_user.profile.bio%>
    <label class="card-text" id="user_bio" style="width:100%;"><i><b>"</b><span onclick="edit_bio()" style="cursor: pointer"><%=bio_display%></span><b>"</b></i></label>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>
<%=render 'shared/user_details_js'%>

app/views/shared/_user_details_js.html.erb
 <script>
 function update_bio(bio_text)
  {
          bio_update_text=$('#user_bio_edit_area').val();
          if(bio_update_text.trim()=="")
          {
            $('#user_bio').html("<i><b>\"</b><span onclick='edit_bio()' style='cursor: pointer'>"+bio_text+"</span><b>\"</b></i>");
          }
          else if(bio_update_text.trim()==bio_text.trim())
          {
            $('#user_bio').html("<i><b>\"</b><span onclick='edit_bio()' style='cursor: pointer'>"+bio_text+"</span><b>\"</b></i>");
          }
          else
          {domain_name=window.location.origin;
            $.ajax({
              type:"post",
              url:domain_name+"/profile/update_bio?update_text="+bio_update_text,
              headers: {
                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
              }
            })
          }
  }
  function edit_bio()
  {
    bio_text=$('#user_bio').find('span').html();
    setTimeout(function() {
      $('#user_bio').html('<textarea id="user_bio_edit_area" style="width:100%;" onfocusout="update_bio(\''+bio_text+'\')">'+bio_text+'</textarea>');
      $('#user_bio_edit_area').focus();
      $('#user_bio_edit_area').keydown(function(e) {
        if(e.keyCode == 13) {
          update_bio(bio_text);
        }
      })
    }, 200);
  }
  </script>