config/routes.rb
 Rails.application.routes.draw do
  	get 'news/index',as:'news'
	require 'sidekiq/web'
	authenticate :user, lambda { |u| u.roles.include? :admin } do
		mount Sidekiq::Web => '/sidekiq'
	end
	mount Ckeditor::Engine => '/ckeditor'
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	resources :notifications,except: [:new, :create, :edit, :update, :destroy, :show] do 
		collection do
			post 'seen',to:'notifications#seen'
		end
	end

	resources :friendship do
		collection do
			get 'allUsers'
			get 'blockedUsers'
			get 'pendingUsers'
		end
		member do 
			get 'showUser'
			get 'addFriend'
			post 'decision/:status/:received_from',to:'friendship#decision',as:"decision"
			post 'block'
			post 'unblock'
			post 'unfriend'
		end
	end

	resources :comments,except: [:index,:new, :create, :edit, :update, :destroy, :show]do
		collection do
			get 'index/:id',to:'comments#index',as: :all
		end
		member do
			get 'new',to:'comments#new', as: :new
			post 'create',to:'comments#create', as: :create
		end
	end
	resources :communities do
		collection do
			get 'public',to:'communities#public'
			get 'private',to:'communities#private_club'
			get 'owned',to:'communities#owned_club'
			post 'toggle_club_admin'
		end
		member do 
			post 'join',to:'communities#join_public'
			post 'requested',to:'communities#ask_private'
			post 'approve_invite/:invitee_id/:status/:invitation',to:'communities#approve_invite',as:"accept_member_into"
			get 'posts'
			get 'members'
			get 'boss'
			get 'invitations'
		end
	end
	 
	resources :profile, except: [:new, :create, :edit, :update, :destroy, :index] do
		collection do
		  patch 'update'
		  get 'edit'
		  post 'update_bio'
		  get "profile_image_carousel",as:"profile_carousel"
		  post "image",as:'image_upload'
		  get 'close_carousel',as:"close_carousel"
		  post 'dp/:id',to:'profile#make_dp',as:"make_profile_image"
		  get "cover_image_carousel",as:"cover_carousel"
		  post "cover_image",as:'cover_image_upload'
		  get 'close_carousel_cover',as:"close_carousel_cover"
		  post 'cover/:id',to:'profile#make_cover',as:"make_cover_image"
		end
	end

	resources :preferences do
		collection do
		  get 'change_panel_color'
		  get 'toggle_background_image'
		  get 'toggle_right_panel'
		  get 'set_background_image'
		end
	end

	resources :blogs do
	end
	
	resources :chatrooms do
		resource :chatroom_users
		resources :messages
		collection do
			get 'all_users'
			post 'get_users_chatroom'
		end
	end

	devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
	root "communities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  layout "lbd4_application"
  before_action :set_club, only: [:show,:join_public,:edit,:update,:destroy,:ask_private,:approve_invite,:posts,:members,:boss,:invitations,:toggle_club_admin]
  def index
  	@my_clubs=current_user.clubs.page(params[:page]).per(10)
    respond_to do |format|
    	format.js{ render partial:"community_router.js.erb",locals:{from: :index} }
      format.html{ render template:"communities/_index.html.erb",locals:{requested_from: "html_request"}}
    end
  end

  def public
  	@all_public_communities=Club.public_clubs(current_user).page(params[:page]).per(10)
  	render partial:"community_router.js.erb",locals:{from: :public}
  end

  def private_club
  	@all_private_communities=Club.private_clubs(current_user).page(params[:page]).per(10)
  	render partial:"community_router.js.erb",locals:{from: :private_club}
  end

  def owned_club
  	@owned_clubs=Club.owned_clubs(current_user).page(params[:page]).per(10)
  	render partial:"community_router.js.erb",locals:{from: :owned_club}
  end

  def new
  	@community=Club.new
  	render partial:"community_router.js.erb",locals:{from: :new}
  end

  def create
  	@club=Club.new(club_params)
  	@club.owner=current_user.id
  	@club.save
    @timeline=@club.reload.timeline
  	render partial:"community_router.js.erb",locals:{from: :create,notice:"Club Created",type:"success"}
  end

  def edit
  	render partial:"community_router.js.erb",locals:{from: :edit}
  end

  def update
  	@club.update(club_params)
  	@my_clubs=Club.where(owner:current_user.id).page(params[:page]).per(10)
  	render partial:"community_router.js.erb",locals:{from: :index,notice:"#{@club.name} Updated",type:"success"}
  end

  def destroy
  	@club.destroy
  	render partial:"community_router.js.erb",locals:{from: :destroy,notice:"#{@club.name} Destroyed",type:"error"}
  end

  def show
    if @club.users.include?(current_user) || @club.owner_is == current_user
      populate_timeline(@club)
      render partial:"community_router.js.erb",locals:{from: :show}
    else
      render partial:"community_router.js.erb",locals:{from: :not_allowoed,notice: "You are not a member of #{@club.name} a private club",type:"error"}
    end
  end


  def join_public
  	@club.users<<current_user
  	render partial:"community_router.js.erb",locals:{from: :join_public,notice:"Joined Successfully"}
  end

  def ask_private
  	@invite=Invitation.create(club:@club,requester:current_user,status: 0,invite_type:0)
  	@club.admins.each do |admin|
  		Notification.create(actor:current_user,recipient:admin,notifiable:@club,action:"requested to join")
  	end
  	#TODO make this code efficient
  	Notification.create(actor:current_user,recipient:@club.owner_is,notifiable:@club,action:"requested to join")
  	render partial:"community_router.js.erb",locals:{from: :ask_private,notice:"Invitation Sent"}
  end
  def approve_invite
    @invitee = User.find_by_id(params[:invitee_id])
  	if params[:status]=="1"
  		@club.users<<@invitee
  		Invitation.find_by_id(params[:invitation]).update(status:1,approver_id:current_user.id)
      Notification.create(actor:current_user,recipient:@invitee,notifiable:@club,action:"Approved your request to join")
  		notice="Accepted"
  		type="success"
  	else
  		Invitation.find_by_id(params[:invitation]).update(status:-1,approver_id:current_user.id)
      Notification.create(actor:current_user,recipient:@invitee,notifiable:@club,action:"Rejected your request to join")
  		notice="Rejected"
  		type="error"
  	end
  	render partial:"community_router.js.erb",locals:{from: :approve_invite,notice:notice,type:type}
  end

  def posts
    populate_timeline(@club)
    render partial:"community_router.js.erb",locals:{from: :posts}
  end

  def members
    @members=@club.users.page(params[:page]).per(10)
    render partial:"community_router.js.erb",locals:{from: :members}
  end

  def boss

    @boss=@club.owner_is
    @admins=@club.admins
    render partial:"community_router.js.erb",locals:{from: :boss}
  end

  def invitations
    @invitations = @club.invitations.pending.page(params[:page]).per(10)
    render partial:"community_router.js.erb",locals:{from: :invitations}
  end

  def toggle_club_admin
    user=User.find_by_id(params[:user_id])
    @club.toggle_club_admin(user)
    render :nothing=>true
  end

  private

  def club_params
  	params.require(:club).permit(:name, :description,:membership_type,:active)
  end

  def set_club
    @club=Club.find_by_id(params[:id])
  end

end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_boss.html.erb
	<div class="card">
		<div class="card-body" style="padding: 30px;">
			<%=@club.description.html_safe%>
		</div>
	</div>
	<hr>
	<h2>Owner</h2>
	<%=render '/shared/user',user:@boss%>
	
	<%unless @admins.empty?%>
	<hr>
	<h4>Admins</h4>
	<%@admins.each do |admin|%>
	<%=render '/shared/user',user:admin%>
	<%end%>
	<%end%>

app/views/communities/_communities.html.erb
<hr>
<%= paginate clubs, :remote => true %>
<%clubs.each do |club|%>
	<%=club.name%>
		<%unless club.owner==current_user.id%>
			<%unless club.include? current_user%>
				
				<%if club.private_club?%>
					<span id="invitation_<%=club.id%>">
					<%unless club.invitation_exist?(current_user)%>
						<%=link_to "Request Membership",requested_community_path(club.id),method: :post,remote:true%>
					<%else%>
						<label style='color:orange;'>Request Sent</label>
					<%end%>
					</span>
				<%else%>
					<%=link_to "Join Now",join_community_path(club.id),method: :post,remote:true%>
				<%end%>
			<%else%>
				<%=link_to "Open",community_path(club.id),remote:true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Opening '+club.name,text_color: 'gold').html_safe%>
			<%end%>
		<%else%>
			<%=link_to "Open",community_path(club.id),remote:true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Opening '+club.name,text_color: 'gold').html_safe%>
			|
			<%=link_to "Edit Club",edit_community_path(club.id),remote: true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Opening '+club.name,text_color: 'gold').html_safe
			%>
			|
			<%=link_to "Destroy",community_path(club.id),method: :delete, data: { confirm: 'Are you sure?' },remote:true%>
		<%end%>
	<hr>
<%end%>
<%= paginate clubs, :remote => true %>

app/views/communities/_community_router.js.erb
<%at_action||=nil%>

<%case from%>
<%when :posts%>
	$('a').removeClass("active");
	$("#posts").addClass("active");
	$('#myTabContent').html("<%= j render partial: 'posts'%>");
<%when :members%>
	$('a').removeClass("active");
	$("#members").addClass("active");
	$('#myTabContent').html("<%= j render partial: 'members'%>");
<%when :boss%>
	$('a').removeClass("active");
	$("#boss").addClass("active");
	$('#myTabContent').html("<%= j render partial: 'boss'%>");
<%when :invitations%>
	$('a').removeClass("active");
	$("#invitations").addClass("active");
	$('#myTabContent').html("<%= j render partial: 'invitations'%>");
<%when :approve_invite%>
	document.getElementById("invitations").click();
<%when :ask_private%>
	$("#invitation_<%=@club.id%>").html("<label style='color:orange;'>Request Sent</label>");
<%when :destroy%>
	document.getElementById("communities_nav").click();
<%when :create%>
	$("#view_id").html("<%=@club.name%>");
	$("#main-timeline").html("<%=j render partial:'show'%>");
<%when :edit%>
	$("#view_id").html("Update Club");
	$("#main-timeline").html("<%=j render partial:'form',locals:{community:@club,action: :update}%>");
<%when :join_public%>
	document.getElementById("communities_nav").click();
<%when :show%>
	$("#view_id").html("<%=@club.name%>");
	$("#main-timeline").html("<%=j render partial:'show'%>");
	$("#posts").addClass("active");
<%when :owned_club%>
	$('a').removeClass("active");
	$("#owned").addClass("active");
	$("#myTabContent").html("<%=j render 'communities',clubs:@owned_clubs%>");
<%when :private_club%>
	$('a').removeClass("active");
	$("#private").addClass("active");
	$("#myTabContent").html("<%=j render 'communities',clubs:@all_private_communities%>");
<%when :public%>
	$('a').removeClass("active");
	$("#public").addClass("active");
	$("#myTabContent").html("<%=j render 'communities',clubs:@all_public_communities%>");
<%when :index%>
	$("#view_id").html("Choose Club");
	$('#communities_nav').parent().addClass("active");
	$("#communities_nav").addClass("active");
	$("#main-timeline").html("<%=j render partial:'index'%>");
	$("#index").addClass("active");
<%when :new%>
	$("#view_id").html("Create Club");
	$("#main-timeline").html("<%=j render partial:'form',locals:{community:@community,action: :create}%>");
<%end%>
<%if notice%>
	new Noty({
		timeout: 1000,
		type: '<%=type rescue "success"%>',
		layout: 'topCenter',
		text: '<%=notice%>'
	}).show();
<%end%>

<%=render 'notifications/notification_panel'%>

app/views/communities/_form.html.erb
<%=form_for community,url:{action: action},remote: true do |f|%>
	<div class="form-group">
		<%=f.label :name%>
		<%=f.text_field :name,class:"form-control"%>
	</div>
	<div class="form-group">
		<%=f.label :description%>
		<%=f.cktext_area :description,class:"form-control"%>
	</div>	
	<div class="form-group">	
		<%=f.label :active,class:"switch"%>
		<%=f.check_box :active%>
	</div>
	<div class="form-group">	
		<%=f.label :membership_type%>
		<%=f.radio_button :membership_type,"public_club"%>
		<%=f.label :membership_type,"Public"%>
		<%=f.radio_button :membership_type,"private_club"%>
		<%=f.label :membership_type,"Private"%>
		<%=f.radio_button :membership_type,"invite_only"%>
		<%=f.label :membership_type,"Invite Only"%>
	</div>		
		<%=f.submit action==:create ? "Create" : "Update" ,class:"btn btn-outline-success",onclick:"return validate();"%>
<%end%>

<script type="text/javascript">
	function validate(){
		return true;
	}
</script>

app/views/communities/_index.html.erb
<%requested_from||=""%>
<%=link_to "New Club",new_community_path,class:"btn btn-success",remote:true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Loading...',text_color: 'gold').html_safe%>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%=link_to "My Clubs",owned_communities_path,class:"nav-link",id:"owned",remote:true%>
  </li>
  <li class="nav-item">
    <%=link_to "Membership",communities_path,class:"nav-link",id:"index",remote:true%>
  </li>
  <li class="nav-item">
    <%=link_to "Public Clubs",public_communities_path,class:"nav-link",id:"public",remote:true%>
    
  </li>
  <li class="nav-item">
   <%=link_to "Private Clubs",private_communities_path,class:"nav-link",id:"private",remote:true%>
  </li>
  
</ul>
    
<div class="tab-content" id="myTabContent">
    <%=render 'communities',clubs:@my_clubs%>
</div>
<%if requested_from=="html_request"%>
<script type="text/javascript">
  $("#view_id").html("Choose Club");
  $('#communities_nav').parent().addClass("active");
  $("#communities_nav").addClass("active");
  $("#index").addClass("active");
</script>
<%end%>

app/views/communities/_invitations.html.erb
<div class="row">
  <%@invitations.each do |invitation|%>
  <div class="col col-md-10">
    <%=render '/shared/user',user:invitation.requester%>
  </div>
  <div class="col col-md-2">
    <%=link_to "Yes",accept_member_into_community_path(invitation:invitation.id,id:@club.id,invitee_id:invitation.requester.id,status:1),method: :post,class:"btn btn-success",remote: true %>
    <%=link_to "No",accept_member_into_community_path(invitation:invitation.id,id:@club.id,invitee_id:invitation.requester.id,status:0),method: :post,class:"btn btn-danger" ,remote: true%>
  </div>
  <%end%>
</div>
<%= paginate @invitations, :remote => true %>

app/views/communities/_members.html.erb
<%owner_view = @club.owner==current_user.id%>
<%= paginate @members, :remote => true %>
<%@members.each do |member|%>
<%=render '/shared/user',user:member,owner_view:owner_view %>
<%end%>
<%= paginate @members, :remote => true %>

app/views/communities/_posts.html.erb
<br>
<center>	
	<div class="btn-group dropdown">
		<button type="button" class="btn btn-outline-secondary disabled">
			New
		</button>
		<button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	            <span class="sr-only">Toggle Dropright</span>
	          </button>

		<div class="dropdown-menu">
		<%= render 'shared/new_post'%>
		</div>
	</div>
</center>
<br>
<%=render 'shared/timeline'%>

app/views/communities/_show.html.erb
<%#=link_to "New Club",new_community_path,class:"btn btn-success",remote:true,onclick: CustomLoader.custom_loader(element_reference_name: 'main-timeline',reference_type:'id',image_url: asset_path('custom_loader/bouncing_balls.gif'),content: 'Loading...',text_color: 'gold').html_safe%>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <%=link_to "Posts",posts_community_path(id:@club.id),class:"nav-link",id:"posts",remote:true%>
  </li>
  <li class="nav-item">
    <%=link_to "Members",members_community_path(id:@club.id),class:"nav-link",id:"members",remote:true%>
  </li>
  <li class="nav-item">
    <%=link_to "About",boss_community_path(id:@club.id),class:"nav-link",id:"boss",remote:true%>
    
  </li>
  <%if @club.private_club? && (@club.has_admin?(current_user)||@club.owner_is == current_user)%>
    <li class="nav-item">
     <%=link_to "Invitations",invitations_community_path(id:@club.id),class:"nav-link",id:"invitations",remote:true%>
    </li>
  <%end%>
  
</ul>
    
<div class="tab-content" id="myTabContent">
    <%=render 'posts'%>
</div>